#!/bin/sh

#--------------------------------------------------------------------------

wallpapers_dir=$(xdg-user-dir PICTURES)/Wallpapers
wallpaper=$(xdg-user-dir RESOURCES)/wallpaper

#---------------------------------------------------------------------------

case "$1" in
"d")
	# delete the image
	read file_name;
	rm $file_name
	;;

"w")
	# set as wallpaper
	read file_name;
	cp $file_name $wallpaper ;
	xwallpaper --zoom $wallpaper
	;;

"g")
	# open the image in GIMP
	tr '\n' '\0' | xargs -0 gimp &
	;;

"m")
	# move the image to wallpapers_dir
	read file_name;
	mv $file_name $wallpapers_dir
	;;

"c")
	# copy the image to wallpapers_dir
	read file_name;
	cp $file_name $wallpapers_dir
	;;

"x")
	# copy the image path to clipboard
	xclip -in -filter | tr '\n' ' ' | xclip -in -selection clipboard
	;;

*)
	;;

esac
