xwallpaper --zoom ~/.local/data/wallpaper &
picom &
sxhkd &
dunst &
xrdb ~/.config/X11/Xresources
xmodmap ~/.config/X11/xmodmaprc && xcape -e "Control_R=Escape"
sh ~/.config/X11/touchpad.sh
qtile start
